name: command
on: 
  workflow_dispatch:
  push: 
    paths:
      - ".github/index.ts"
jobs:
  command:
    name: Use Linux commands 2
    runs-on: ubuntu-latest
    steps:
      - name: Show ubuntu details
        run: lsb_release -a
      - name: Inspect files before checkout
        run: ls -la
      - name: show current directory before checkout
        run: pwd
  